"""Domain-specific repository contracts and backend-neutral composition."""
from typing import Protocol, Any
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from server.tasks import Task, TaskStep, TaskEvent


class WorkspaceRepository(Protocol):
    def create(self, name: str, description: str = '') -> Any: ...
    def get(self, workspace_id: str) -> Any: ...
    def documents(self, workspace_id: str) -> list: ...


class SessionRepository(Protocol):
    def create(self, **fields) -> Any: ...
    def get(self, session_id: str) -> Any: ...
    def load_messages(self, session_id: str) -> list: ...
    def save_messages(self, session_id: str, messages: list) -> None: ...


class MemoryRepository(Protocol):
    def create(self, memory) -> Any: ...
    def get(self, memory_id: str, owner_id: str = 'local_default') -> Any: ...
    def retrieve_memories(self, query: str, workspace_id: str | None = None) -> list: ...


class TaskRepository(Protocol):
    def create(self, task: 'Task') -> 'Task': ...
    def get(self, task_id: str) -> 'Task': ...
    def transition(self, task_id: str, status: str, *, error=None) -> 'Task': ...
    def steps(self, task_id: str) -> list['TaskStep']: ...
    def events(self, task_id: str) -> list['TaskEvent']: ...


class DatasetRepository(Protocol):
    def get(self, workspace_id: str, dataset_id: str) -> Any: ...
    def list(self, workspace_id: str) -> list: ...


class ArtifactRepository(Protocol):
    def artifact(self, artifact_id: str) -> Any: ...
    def artifacts(self, task_id: str) -> list: ...


class ApprovalRepository(Protocol):
    def approval(self, record_id: str) -> dict: ...
    def decide(self, approval_id: str, decision: str, **options) -> dict: ...


class ToolExecutionRepository(Protocol):
    def execution(self, record_id: str) -> dict: ...
    def claim(self, execution_id: str) -> tuple: ...


class AgentRunRepository(Protocol):
    def run(self, run_id: str) -> dict: ...
    def runs(self, task_id: str) -> list: ...


class DelegationRepository(Protocol):
    def delegation(self, delegation_id: str) -> dict: ...
    def delegations(self, supervisor_run_id=None, task_id=None) -> list: ...


class MCPRepository(Protocol):
    def save(self, config) -> Any: ...
    def list(self) -> list: ...


class RepositoryFactory:
    """Shared domain implementations use SQLite or pooled SQLAlchemy query ports.

    Domain models, validation, dedupe and service contracts stay in domain stores;
    this factory never owns their business logic. Synchronous methods execute in
    FastAPI/worker threads. Queue transactions use AsyncSession directly.
    """
    def __init__(self, source):
        self.source = source

    def build(self, repository_type, *args):
        return repository_type(self.source, *args)
